name: CodePress Review

on:
  pull_request:
    types: [opened, reopened, review_requested] #synchronize
  issue_comment:
    types: [created]
  workflow_dispatch: # Allow manual triggering

permissions:
  pull-requests: write
  contents: read
  issues: read

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: CodePress Review
        uses: quantfive/codepress-review@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          model_provider: "gemini"
          model_name: "gemini-2.5-flash"
          gemini_api_key: ${{ secrets.GEMINI_API_KEY}}
          # All trigger configurations use sensible defaults
          # + synchronize event runs automatically when included in workflow
